from setuptools import setup, find_packages

setup(
    name="djtello-digital-twin",
    version="0.1.0",
    description="Digital twin simulation of a DJI Tello drone with AI agent",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/djtello-digital-twin",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.20.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "pygame>=2.0.0",
        "gymnasium>=0.26.0",
        "stable-baselines3>=1.5.0",
        "torch>=1.10.0",
        "pybullet>=3.2.1",
        "opencv-python>=4.5.0",
        "pillow>=8.0.0",
        "tqdm>=4.60.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
